### ISSUE TITLE
[bug] .gif images fail to load

### ISSUE THREAD

**Issue by silicone-fig** [micahlt/wasteof.mobile#11]
App fails to load .gif image sequence and returns single frame instead.

**Comment by micahlt** [comment]
This seems to be a limitation as far as GIF files are rendered natively on Android.  I'll look into solutions to this problem, but for now work will continue to go into the new rebuild of wasteof.mobile.

**Comment by micahlt** [comment]
Fix for this should be Fresco:.  See https://stackoverflow.com/a/59226516/10806546 for reference.

**Comment by micahlt** [comment]
Resolved in c6de802.
