### ISSUE TITLE
[feat] Define a universal API url variable

### ISSUE THREAD

**Issue by Chiroyce1** [micahlt/wasteof.mobile#19]
### The Problem

Take for example [this file](https://github.com/micahlt/wasteof.mobile/blob/reactnative/src/UserModal.js), there are multiple instances where `https://api.wasteof.money` and `https://wasteof.money` are mentioned, in case of an extremely unlikely change in these urls' domains, there should be a way to easily modify them instead of manually going through every file that references them (sure search and replaces makes it easier but will be ugly to view all these changes in a git diff)

### Possible fix

Export these urls as a variable from a single file, and import them as required. Please do consider other ways you can define these urls in one place as well, as I'm not too familiar with how React Native handles it.

**Comment by tushar1-000** [comment]
Hi, @micahlt  I want to work with this issue and this will be my first contribution to the open source. 
These will be the steps I will follow to solve this issue .
1. Create new file 'apiName.js'.
2. creating the variable and putting the apiURL there and exporting it.
3. Importing to all the files where we have used the API URL.

**Comment by micahlt** [comment]
You are welcome to take this on @tushar1-000!

**Comment by tushar1-000** [comment]
ok I will be working on it

**Comment by micahlt** [comment]
I'm testing your code now.
