### ISSUE TITLE
[feat] render svg profile pictures

### ISSUE THREAD

**Issue by TheAwesome98-Real** [micahlt/wasteof.mobile#22]
currently they show as an empty image

**Comment by micahlt** [comment]
Is that something wasteof actually supports?

**Comment by TheAwesome98-Real** [comment]
> Is that something wasteof actually supports?

default profile picture is svg

**Comment by micahlt** [comment]
As of now, this isn't a priority since it's a relatively niche use case.

**Comment by TheAwesome98-Real** [comment]
so people with default profile pictures will just be blank?

**Comment by micahlt** [comment]
Yes, as of now.  They'll appear in-app as a wasteof-colored circle.  If anything it encourages people to add a profile picture.
