### ISSUE TITLE
[bug] comments duplicate when replying

### ISSUE THREAD

**Issue by Quantum-Codes** [micahlt/wasteof.mobile#34]
## Bug
**Visual bug**: When we add a comment, the rest of  comments visually creates a copy of itself. (fixes after reloading page)

### Commenting:
![Screenshot_20230530_153116_wasteofmobile](https://github.com/micahlt/wasteof.mobile/assets/87054411/428e1852-08d9-42dc-a61d-92fa89042ec8)
(Commented in order: A, B, C. After each comment, remaining comments duplicated themselves.)
1. First comment = A (no problem here)
2. Second comment = B (current with visual bug = A B A. Actual = AB. here "A" duplicated itself)
3. Third comment = C (current= ABA C ABA. Actual = ABC. ABA group duplicated)
### Replying:
![Screenshot_20230530_151025_wasteofmobile](https://github.com/micahlt/wasteof.mobile/assets/87054411/b94c6860-46e4-41df-9832-de6082d8052d)
(Replying does the same and also copies the parent chain itself)

**Comment by micahlt** [comment]
Thanks for the report!  This appears to be a valid bug, and I'll work on it.

**Comment by micahlt** [comment]
This was fixed in bc03999c29262e6c48a034c2dcbef5a26d861d6b at version [2.5.0](https://github.com/micahlt/wasteof.mobile/releases/tag/2.5.0).  Can you confirm that you are no longer seeing the issue @Quantum-Codes?

**Comment by Quantum-Codes** [comment]
Fixed, thank you!
