### ISSUE TITLE
[bug] Changing your username outside the app breaks the feed

### ISSUE THREAD

**Issue by 8BitOSC** [micahlt/wasteof.mobile#43]
Exactly what the title says, although I think it's extremely likely that this breaks more than the feed.
Everything works again if you:
A. Change your username back to what it was originally (shown in attached video)
or B. Log out and log back in again with your new username.

https://github.com/micahlt/wasteof.mobile/assets/75950907/ca03aad2-58a5-419d-bdee-f50fd8714213

(this is an old video, but I can confirm this did happen again when I rebranded a few weeks ago)

**Comment by micahlt** [comment]
This won't be worked on considering it's a very niche use case and the settings page explicitly says that changing the username may result in undesirable consequences.  Signing out and signing back in to wasteof for Android should fix this issue.
